<a href="https://colab.research.google.com/github/HowardChen0211/gisPy/blob/main/Week1_Intro_map.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
#  !pip install geopandas

Requirement already satisfied: geopandas in /usr/local/lib/python3.12/dist-packages (1.1.4)
Requirement already satisfied: numpy>=1.24 in /usr/local/lib/python3.12/dist-packages (from geopandas) (2.0.2)
Requirement already satisfied: pyogrio>=0.7.2 in /usr/local/lib/python3.12/dist-packages (from geopandas) (0.13.0)
Requirement already satisfied: packaging in /usr/local/lib/python3.12/dist-packages (from geopandas) (26.3)
Requirement already satisfied: pandas>=2.0.0 in /usr/local/lib/python3.12/dist-packages (from geopandas) (2.2.3)
Requirement already satisfied: pyproj>=3.5.0 in /usr/local/lib/python3.12/dist-packages (from geopandas) (3.7.2)
Requirement already satisfied: shapely>=2.0.0 in /usr/local/lib/python3.12/dist-packages (from geopandas) (2.1.2)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.12/dist-packages (from pandas>=2.0.0->geopandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.12/dist-packages (from pandas>=2.0.0->geopandas) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.12/dist-packages (from pandas>=2.0.0->geopandas) (2026.3)
Requirement already satisfied: certifi in /usr/local/lib/python3.12/dist-packages (from pyogrio>=0.7.2->geopandas) (2026.7.22)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.12/dist-packages (from python-dateutil>=2.8.2->pandas>=2.0.0->geopandas) (1.17.0)

In [ ]:
gpd.__version__

'1.1.4'

In [ ]:
import os, zipfile
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import geopandas as gpd

import mapclassify # need for thematic map classification

#will display all output not just last command
from IPython.core.interactiveshell import InteractiveShell
InteractiveShell.ast_node_interactivity = "all"

In [ ]:
# shp is a form of 向量資料
gdf_Rail = gpd.read_file("/content/drive/MyDrive/GIS_2026 Fall/Rail/RAIL.shp", encoding = "utf-8")
gdf_Rail.head()

,RAILID,RAILNAME,RAILTYPE,MDATE,DEFINITION,geometry
0,O0000000001,臺鐵內灣線,2,201311,0,"LINESTRING (248537.856 2744654.392, 248582.66 ..."
1,O0000000002,臺鐵內灣線,2,201311,0,"LINESTRING (252762.399 2741652.649, 252762.087..."
2,O0000000003,臺鐵海岸線(海線),2,201311,0,"LINESTRING (238293.482 2736274.722, 238293.707..."
3,P0000000004,臺鐵縱貫線南段,2,201609,0,"LINESTRING (198052.863 2620124.003, 198062.309..."
4,P0000000003,臺鐵縱貫線南段,2,201608,0,"LINESTRING (197498.964 2619431.837, 197581.785..."

In [ ]:
sample = gdf_Rail.sort_values(by="MDATE")
sample.head()

,RAILID,RAILNAME,RAILTYPE,MDATE,DEFINITION,geometry
605,M0000000006,臺鐵集集線,2,200903,0,"LINESTRING (227966.379 2635798.635, 227958.213..."
603,M0000000004,臺鐵集集線,2,200903,0,"LINESTRING (227986.868 2635797.885, 228002.272..."
604,M0000000005,臺鐵集集線,2,200903,0,"LINESTRING (227966.379 2635798.635, 227990.984..."
606,M0000000007,臺鐵集集線,2,200903,0,"LINESTRING (227991.07 2635800.179, 227991.446 ..."
607,M0000000008,臺鐵集集線,2,200903,0,"LINESTRING (227991.07 2635800.179, 227991.348 ..."

In [ ]:
!wget -q -O nj-counties.zip https://docs.google.com/uc?id=1xJDhcRCkgv7k4tNCa72Oog5bohV6dTB2&export=download

In [ ]:
zip_ref = zipfile.ZipFile('/content/nj-counties.zip', 'r'); zip_ref.extractall(); zip_ref.close() #just unzipping
njC0=gpd.read_file('nj_counties.shp') #load the shapefile with gpd as njC

BadZipFile: File is not a zip file